version: "3.7"

services:
  redis:
    image: redis
    container_name: redis

  flask:
    build: ./flask
    container_name: flask
    environment:
      - FLASK_CONFIG=production
    restart: always
    expose:
      - 8080
    depends_on:
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask
